### ISSUE TITLE
 can't find ValueFormatter

### ISSUE THREAD

**Issue by Alexxiaopang** [AppDevNext/AndroidChart#114]
from PhilJay/MPAndroidChart update to AppDevNext/AndroidChart

can't find com.github.mikephil.charting.formatter.ValueFormatter

It is used a lot in the project, so the change is huge

**Comment by hannesa2** [comment]
With bc0be2cfe13e32 this was changes on upstream master, but it is, till now, not released there.
Please see commit details, what to do now, e.g https://github.com/AppDevNext/AndroidChart/commit/bc0be2cfe13e32a5d8adefaa507e3512d22d85fb#diff-81ee5abd28cbe15bbaa9a6f0bd231c5d27e3c9ab9f8c9a9399dfb477b3b13b5cL101

Mostly a change from `ValueFormatter` to `IAxisValueFormatter` is a valid way
