### ISSUE TITLE
Kotlin conversions made all classes 'Java Final'

### ISSUE THREAD

**Issue by Hessesian** [AppDevNext/AndroidChart#188]
It's often the case that classes like "LineData" and sucha are extended in client apps for customized behaviour, converting it to kotlin made them final and non extensible, please make them open to ensure backwards compatibility

**Comment by hannesa2** [comment]
https://github.com/AppDevNext/AndroidChart/pull/189

**Comment by hannesa2** [comment]
https://github.com/AppDevNext/AndroidChart/releases/tag/3.1.0.19
