### ISSUE TITLE
Rounded bar chart renderer

### ISSUE THREAD

**Issue by Paget96** [AppDevNext/AndroidChart#237]
You can merge these! 

https://github.com/PhilJay/MPAndroidChart/pull/5420

**Comment by hannesa2** [comment]
Here it is https://github.com/AppDevNext/AndroidChart/pull/238

**Comment by hannesa2** [comment]
https://github.com/PhilJay/MPAndroidChart/pull/5420#issuecomment-2183028403
> There is crash when we use FloatArray for Y values.
> Crash happens here, as we don't have y, instead yVals
>
>  ```if ((dataSet.getEntryForIndex(j / 4).y < 0 && roundedNegativeDataSetRadius > 0)) {```
>
> This is only needed to make it perfect

Where should be this applied ? Best would be a pull request
