### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by ZooMMaX** [AppDevNext/AndroidChart#76]
Please publish the library to maven central

**Comment by hannesa2** [comment]
I see the issue, because jitpack.io is done since 24 h and not everyone has the lib in cache. 
To be honest, till now I was to lazy to publish to _macenCentral()_ and I've the fear that I've make a hard fork of upstream because of this. So the question is, what's the minimum change to make it work ?

**Comment by hannesa2** [comment]
Ok, I did the first step https://issues.sonatype.org/browse/OSSRH-87292

**Comment by drachim-dev** [comment]
We are depending on this library and your fork of paho.mqtt.
As jitpack.io has been proven to be unreliable, it would be awesome if you could publish to mavenCentral or github packages :)
Thanks for maintaining those libraries!

**Comment by hannesa2** [comment]
jitpack.io is back again

**Comment by hannesa2** [comment]
@drachim-dev 

> it would be awesome if you could publish to mavenCentral or github packages :)

Sure, I see this issue as well. Btw, helping hands are always welcome. I currently try to use github packages, but I don't know exactly how to use it. I only know since 1h about the existence. Please see my experiments https://github.com/AppDevNext/AndroidChart/pull/78
With `mavenCentral()` I wait for a [response](https://github.com/AppDevNext/AndroidChart/issues/76#issuecomment-1363696692)

**Comment by drachim-dev** [comment]
> @drachim-dev
> 
> > it would be awesome if you could publish to mavenCentral or github packages :)
> 
> Sure, I see this issue as well. Btw, helping hands are always welcome. I currently try to use github packages, but I don't know exactly how to use it. I only know since 1h about the existence. Please see my experiments #78 With `mavenCentral()` I wait for a [response](https://github.com/AppDevNext/AndroidChart/issues/76#issuecomment-1363696692)
Same for me, heard about it in the jitpack issue!
There has just been a [reply](https://issues.sonatype.org/browse/OSSRH-87292?focusedCommentId=1228308&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1228308) to your submit on mavenCentral btw

**Comment by ZooMMaX** [comment]
Unfortunately I don't know how to publish to mavencentral using gradle. I mainly use maven builder and there i know how to publish

**Comment by ZooMMaX** [comment]
Okay. The sonotype replied that the group id was incorrect. Change from mxtracks.info to info.mxtracks

**Comment by ZooMMaX** [comment]
> Ok, following [this guide](https://dev.to/julbrs/beginner-guide-to-maven-central-publishing-3jio#:~:text=Beginner%20guide%20to%20Maven%20Central%20publishing%201%20First,of%20...%205%20References%20...%206%20Conclusion%20), I did the first step https://issues.sonatype.org/browse/OSSRH-87292

https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by hannesa2** [comment]
As a first step https://github.com/AppDevNext/AndroidChart/releases/tag/3.1.0.12 is now published 
* on jitpck.io and 
* on [Github packages](https://github.com/AppDevNext/AndroidChart/packages/1758223)

Please read [README.md](https://github.com/AppDevNext/AndroidChart#gradle-setup-with-github-package) for details

Next will be `mavenCentral()` I hope it comes with better error messages like Github packages . There the error messages were somehow misleading

**Comment by ZooMMaX** [comment]
Fine. Now you have an account in maven central. It remains to configure the gradle for publishing packages)

Also, I think you'll have to change the package name to info.mxtracks.etc...

**Comment by hannesa2** [comment]
I'm not 100 % convinced if the huge afford make sense. When the upstream maintainer change something, all my afford is pointless. The risk is high !

For me the current situation is fine, that means that the publish to `mavenCentral()` I do for someone else. Any help would be very appreciate https://github.com/AppDevNext/AndroidChart/pull/80

**Comment by hannesa2** [comment]
Any help is welcome here https://github.com/AppDevNext/AndroidChart/pull/82

**Comment by hannesa2** [comment]
This is the most promising blueprint https://github.com/ViliusSutkus89/Sample_Android_Library-MavenCentral-Instrumented_Tests/ but I give up now. (I wasted to much lifetime)
This https://github.com/AppDevNext/AndroidChart/pull/85 and https://github.com/AppDevNext/AndroidChart/pull/82 are able to push to https://s01.oss.sonatype.org/#stagingRepositories 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3314607/209789533-3183a2d6-203d-4ffb-bd8b-13f5a7be62aa.png">

But I've no clue how to bring it to https://oss.sonatype.org or how to use it like 
`implementation 'info.mxtracks:chart:3.1.0.12'`

**Comment by hannesa2** [comment]
It's better then nothing https://github.com/AppDevNext/AndroidChart#gradle-setup-with-sonartype-snapshot
